# Development Environment Configuration
# For local development and testing

checkmk:
  server_url: "http://localhost:5000"
  username: "cmkadmin"
  password: "cmkadmin"
  site: "dev"
  max_retries: 2
  request_timeout: 10

llm:
  # Use a faster, cheaper model for development
  # Option 1: OpenAI
  openai_api_key: "sk-dev-api-key"
  default_model: "gpt-3.5-turbo"
  
  # Option 2: Anthropic (uncomment to use instead)
  # anthropic_api_key: "sk-ant-your-dev-key"
  # default_model: "claude-3-haiku-20240307"

# UI Configuration for development
ui:
  theme: "colorful"  # Vibrant colors for development
  use_colors: true
  auto_detect_terminal: true
  custom_colors:
    # Override some colors for better development visibility
    info: "bright_blue"
    success: "bright_green"

default_folder: "/development"
log_level: "DEBUG"